export enum ApiEntity {
  ATTRIBUTE = 'attribute',
  LANGUAGE = 'language',
  STATUS = 'status',
  DIRECTORY = 'directory',
  POINT = 'point',
  MEASURE = 'measure',
  USER = 'user',
  GROUP = 'group',
  SIGN_IN = 'sign-in',
  BLOCK = 'block',
  ELEMENT = 'element',
  SECTION = 'section',
  FORM = 'form',
  RESULT = 'result',
  COLLECTION = 'collection',
  FILE = 'file',
}
